### ISSUE TITLE
Error when choosing custom namespace

### ISSUE THREAD

**Issue by vizo** [devisephp/bootstrap#4]
I choose custom namespace "timtrade" during installation and after it completes i get in error log:

```
[Thu Sep 03 00:17:35.305449 2015] [:error] [pid 20842] [client 192.168.1.100:43697] PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class Timtrade\\Http\\Kernel does not exist' in /home/vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Container/Container.php:736\nStack trace:\n
#0 /home/vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct('Timtrade\\\\Http\\\\K...')\n
#1 /home/vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\\Container\\Container->build('Timtrade\\\\Http\\\\K...', Array)\n
#2 /home/vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\\Container\\Container->make('Timtrade\\\\Http\\\\K...', Array)\n
#3 /home/vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Container/Container.php(216): Illuminate\\Foundation\\Application->make('Timtrade\\\\Http\\\\K...', Array)\n
#4 /home/vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Container/Container.php(733 in /home/vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 736, referer: http://tehsi.com/timtrade.si/install/create-user
```

When composer update:

```
 [RuntimeException]                                                                                                                             
  Error Output: PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class Timtrade\Console\Kernel does not exist' in /home  
  /vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Container/Container.php:736                                             
  Stack trace:                                                                                                                                   
  #0 /home/vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct('Ti  
  mtrade\\Consol...')                                                                                                                            
  #1 /home/vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->  
  build('Timtrade\\Consol...', Array)                                                                                                            
  #2 /home/vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Containe  
  r->make('Timtrade\\Consol...', Array)                                                                                                          
  #3 /home/vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Container/Container.php(216): Illuminate\Foundation\Applicatio  
  n->make('Timtrade\\Consol...', Array)                                                                                                          
  #4 /home/vivizio/workspace/timtrade.si/vendor/laravel/framework/src/Illuminate/Container/Container.php(733) in /home/vivizio/workspace/timtra  
  de.si/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 736               
```

Maybe i had to choose "Do you want override all Devise configs?" to "yes" during installation?

**Comment by dolbex** [comment]
@vizo - First, your namespace should be uppercase. So maybe "TimTrade" or "Timtrade". Currently, with Devise Bootstrap (fresh install) I'm getting a successful install with the following results just as an example:

```
<?php

namespace timtrade\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \timtrade\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \timtrade\Http\Middleware\VerifyCsrfToken::class,
    ];

    /**
     * The application's route middleware.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'devise.permissions' => \Devise\Pages\Http\Middleware\Permissions::class,
    ];
}
```

Also double checked scripts by running composer update and getting the following:

```
vagrant@homestead:~/Code/bootstraptest/bootstrap$ composer update
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
> php artisan optimize
Generating optimized class loader
vagrant@homestead:~/Code/bootstraptest/bootstrap$ 
```

Could have been something we updated as this is a pretty old issue.
